 [variables]
 DOTNET_CLI_TELEMETRY_OPTOUT = "true"
 
 [phases.setup]
 nixPkgs = ["dotnet-sdk_8"]
 
[phases.install]
commands = [
  "dotnet restore"
]

[phases.build]
commands = [
  "dotnet publish API/API.csproj -c Release -o /app/publish"
]
 
 [start]
command = "dotnet /app/publish/API.dll"
